### PR TITLE
F curvature

### PR DESCRIPTION
**Pull request by weilandtd**
- Implementation of BondedQuintets
- Implementation of FCuvature a force that is based on the gradient of the squared mean curvature 
  Fij = kA*Grad_{r_ij}(H^2) 
- Minor improvements in FAngular (comments / variable names)
- Testmodule for FCuvature
- Edited Author File

### CODE REVIEW

**Comment by kauzlari** [comment]
Please make the following changes before pull-requesting again:
- AUTHORS are sorted alphabetically according to last name
- change the year in every modified file to 2015
- confirm that a small test with more than one species also works
- add a test to the testsuite (ideally using more than one species)

**Comment by weilandtd** [comment]
- AUTHORS reordered
- years modified in all files added or changed.
- Test in the testsuite changed. FCurverutre is now used in simulation that simulates a membrane in contact with a simple DPD-Fluid.

**Comment by kauzlari** [comment]
Sorry, but I still have some issues:
- Are you sure that the current test only runs for a few seconds? It is hard for me to believe with 1000 timesteps and 1100 particles.
- Did you test the quintet-stuff with more than one species WITHIN the quintets?
- Can you put such a test into the testsuite and your test with a single species in the membrane into the examples? Sorry to ask for that, but multi-species-tests are critical. Many bugs only show up in such a case. Take care how particles are indexed in the connector file in such a case. It goes like (0..9) for the 10 particles belonging to the first species and then (10..14) for the 5 particles belonging to the second species. Ideally, you extend your current test by "simply" changing the species of some particles of your choice in the quintets. The interactions in the quintet and with the fluid may remain identical, except that you now have to define them for additional species-interactions. In this way you should get exactly the same output (if kinetic energy of all species in the membrane is properly measured and summed) and can easily compare for correctness. I know, this is a bit of work, but necessary for a reliable code.

**Comment by weilandtd** [comment]
- Test runs 5 secs
- Test gives the same results as with 1 species in the membrane
- Test with a membrane of two species is implemented in the testsuite

**Pull request merged**
